export type GitHubRepo = {
  id: number;
  name: string;
  stargazers_count: number;
  html_url: string;
  homepage: string;
  description: string;
  created_at: string;
  updated_at: string;
  topics: string[];
  license_name: string;
  license_url: string;
  language: string;
  license_key: string;
  license: any;
  stars: number;
  home_page: string;
  license_spdx_id: string;
  files: string[];
};
