import Link from "next/link"; // Import the Link component from the Next.js framework.
import Image from "next/image"; // Import the Image component from Next.js.
import type { Metadata } from "next"; // Import the Metadata type from Next.js.
import socialLinks from "./links.json"; // Import an array of social links from a local JSON file.

export const metadata: Metadata = { // Define metadata for the page.
  title: "Find Me On The Internet!", // Title of the page.
  description: "Generated by create next app", // Description of the page.
};

export default function Social() { // Define a default export function named Social.
  return (
    <div className="min-h-screen flex items-center justify-center">
      {/* Create a container div with minimum height to center content vertically */}
      <div className="p-8 space-y-3 rounded-2xl">
        {/* Create a container div with padding and spacing */}
        <div className="flex items-center justify-center">
          {/* Create a div to center content horizontally */}
          <Image
            unoptimized={true}
            src={"/icon.png"}
            alt="Picture of the author"
            width={120}
            height={120}
          />
          {/* Display an image with specified dimensions */}
        </div>
        <div className="pb-5 text-center text-xs text-white font-mono font-bold tracking-tight select-none">
          You can reach me through these links
        </div>
        {/* Display a text message */}
        <div className="space-y-2 mt-4">
          {/* Create a container for social links */}
          {socialLinks.map((link, index) => (
            // Map through the socialLinks array and create a Link for each link.
            <Link legacyBehavior key={index} href={link.href}>
              {/* Create a Link component with the 'href' attribute from the array */}
              <a
                className="block w-full rounded-lg bg-zinc-800 sm:px-32 md:px-60 py-2 text-center text-white lowercase hover:scale-105 hover:bg-zinc-700 select-none"
                target="_blank"
              >
                {link.name}
              </a>
              {/* Create an anchor element with styling and 'target="_blank"' to open links in a new tab */}
            </Link>
          ))}
        </div>
      </div>
    </div>
  );
}
